version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.6
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket lambda-deployment-pipeline-demo --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml