AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: lambda_function.py
      Timeout: 300
      MemorySize: 200
      Events:
        UserLogin:
          Type: Api
          Properties:
            Path: /login
            Method: POST
            RestApiId:
              Ref: UserAPI
            RequestModel:
              Model: User
  UserAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Test
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Models:
        User:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
Outputs:
  UserLoginApi:
    Value: !Sub "https://${UserAPI}.execute-api.${AWS::Region}.amazonaws.com/Test/login"
  MyFunction:
    Value: !GetAtt MyFunction.Arn
  MyFunctionIamRole:
    Value: !GetAtt MyFunctionRole.Arn
